;Script generated by the Inno Setup Script Wizard. 
;SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;Non-commercial use only
#define MyAppName "project-java-integration"
#define MyAppVersion "1.0"
#define MyAppPublisher "Roberta Alanis Andrade Nogueira"
#define ProjectDir "..\..\..\..\.."
[Setup] 
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2B7B5B21-F844-454E-927F-944B70867AF1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName}{#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\project-java-integration
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile={#ProjectDir}\LICENSE.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=project-java-integration
SetupIconFile=logo_eletra.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}";GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#ProjectDir}\target\jfx\native\project-java-integration-1.0.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#ProjectDir}\target\jfx\native\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\project-java-integration"; Filename: "{app}\project-java-integration-1.0.exe" 
Name: "{userdesktop}\project-java-integration"; Filename: "{app}\project-java-integration-1.0.exe";IconFilename: "{app}\logo_eletra.ico";

[Run] 
Filename: "{app}\project-java-integration-1.0.exe"; Parameters: "-install -svcName ""project-java-integration"" -svcDesc ""project-java-integration"" -mainExe ""project-java-integration-1.0.exe""";