;Script generated by the Inno Setup Script Wizard. 
;SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
;Non-commercial use only
#define MyAppName "project-java-integration"
#define MyAppVersion "1.0"
#define MyAppPublisher "Roberta Alanis Andrade Nogueira"
[Setup] 
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{2B7B5B21-F844-454E-927F-944B70867AF1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}{#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\project-java-integration
DisableStartupPrompt=Yes
DisableDirPage=Yes
DisableProgramGroupPage=Yes
DisableReadyPage=Yes
DisableFinishedPage=Yes
DisableWelcomePage=Yes
DefaultGroupName=Eletra Energy Solutions
; Remove the following line to run in administrative install mode (install for all users).
OutputBaseFilename=project-java-integration
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest
SetupIconFile=project-java-integration\project-java-integration.ico
UninstallDisplayIcon={app}\project-java-integration.ico
UninstallDisplayName=project-java-integration
WizardImageStretch=yes
WizardSmallImageFile=project-java-integration-setup-icon.bmp
ArchitecturesInstallIn64BitMode=

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}";GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "project-java-integration\project-java-integration.exe"; DestDir: "{app}"; Flags: ignoreversion;
Source: "project-java-integration\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\project-java-integration"; Filename: "{app}\project-java-integration.exe"; IconFilename: "{app}\project-java-integration.ico";
Name: "{commondesktop}\project-java-integration"; Filename: "{app}\project-java-integration.exe";IconFilename: "{app}\project-java-integration.ico";

[Run]
Filename: "{app}\project-java-integration.exe"; Description:"{cm:LaunchProgram,project-java-integration}"; Flags: nowait postinstall skipifsilent;
Filename: "{app}\project-java-integration.exe"; Parameters: "-install -svcName ""project-java-integration"" -svcDesc ""project-java-integration"" -mainExe ""project-java-integration.exe""";Flags: nowait;

[UninstallRun]
Filename: "{app}\uninstaller"; Parameters: "-uninstall -svcName project-java-integration -stopOnUninstall";